config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users do
    member do
      get :following
      get :followers
      get :likes
    end
  end
  resources :users, only: [:show]
  resources :purrs
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  get '/home', to: 'pages#home'
  get '/explore', to: 'pages#explore'
  root "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root to: "/home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :purr
  validates :user_id, presence: true
  validates :purr_id, presence: true
end

app/models/purr.rb
class Purr < ApplicationRecord
  belongs_to :user
  validates_associated :user

  has_many :likes, dependent: :destroy
  
  validates :content, length: {maximum: 140}, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :purrs, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  has_many :likes, dependent: :destroy
  has_many :liked_purrs, through: :likes, source: :purr

  validates :name, length: {maximum: 50}, presence: true
  validates :username, length: {maximum: 15}, presence: true, uniqueness: true,
            format: {with: /[a-z0-9_]{1,15}/i, message: "can only contain letters, numbers and '_'"}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def follow(other)
    active_relationships.create!(followed_id: other.id)
  end

  def unfollow(other)
    active_relationships.find_by(followed_id: other.id).destroy
  end

  def following?(other)
    following.include?(other)
  end

  def self.random_2_not(user)
    records = User.where.not(id: user.id)

    unless user.following.empty?
      records = records.where("id not in (?)", user.following.pluck(:id))         
    end

    records.order(Arel.sql('random()')).limit(2) 
  end

  def like(post)
    self.likes.create!(user_id: self.id, purr_id: post.id)
  end

  def unlike(post)
    self.likes.find_by(purr_id: post.id).destroy
  end

  def likes?(post)
    self.likes.find_by(purr_id: post.id) ? true : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :new_purr

  def new_purr
    if user_signed_in?
      @new_purr = Purr.new
    end
  end

  def set_to_follow_users
    @to_follow_users = User.random_2_not(current_user)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    purr = Purr.find(params[:purr_id])
    current_user.like(purr)
    flash[:notice] = "You liked this purr!"
    redirect_back fallback_location: "/home"
  end

  def destroy
    purr = Like.find(params[:id]).purr
    current_user.unlike(purr)
    flash[:notice] = "You unliked this purr!"
    redirect_back fallback_location: "/home"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_to_follow_users, except: [:index]

  def home
    @user = current_user
    @purrs = Purr.where("user_id IN (?) OR user_id = ?",  @user.following_ids, @user.id).order("id DESC")
  end

  def explore
    @user = current_user
    @purrs = Purr.all.order("id DESC")
  end

  def index
    if user_signed_in?
      redirect_to home_url
    end
  end
end

app/controllers/purrs_controller.rb
class PurrsController < ApplicationController
  before_action :authenticate_user!

  def create
    @purr = Purr.new(purr_params)
    if @purr.save
      redirect_to home_url, notice: "Your Purr has been sent."
    else
      redirect_to home_url, alert: "Invalid form."
    end
  end
  
  def edit
    @purr = Purr.find(params[:id])
    if not @purr.user.id.equal? current_user.id
      flash[:notice] = "Not allowed to edit that purr"
      redirect_back fallback_location: "/home"
    end
  end

  def update
    @purr = Purr.find(params[:id])

    if @purr.user.id.equal? current_user.id
      if @purr.update_attributes(purr_params)
        flash[:notice] = "Purr successfully updated!"
        redirect_back fallback_location: "/home"
      else
        flash[:notice] = "Unable to update purr."
        redirect_back fallback_location: "/home"
      end
    else
      flash[:notice] = "Not allowed to edit that purr."
      redirect_back fallback_location: "/home"
    end
  end

  def destroy
    purr = Purr.find(params[:id])
    
    if not current_user.id == purr.user.id
      flash[:notice] = "Not allowed to delete that purr."
      redirect_back fallback_location: "/home"
    else
      purr.destroy
      flash[:notice] = "Purr successfully deleted!"
      redirect_back fallback_location: "/home"
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def purr_params
      params.require(:purr).permit(:content, :user_id)
    end
end

app/controllers/registration_controller.rb
class RegistrationsController < Devise::RegistrationsController 

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 

  protected

  def after_sign_up_path_for(user)
    '/home'
  end

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create 
    user = User.find(params[:followed_id])
    current_user.follow(user)
    flash[:notice] = "User was successfully followed!"
    redirect_back fallback_location: "/home"
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    flash[:notice] = "User was successfully unfollowed!"
    redirect_back fallback_location: "/home"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_to_follow_users

  def show
    @purrs = @user.purrs.order("id DESC")
    set_to_follow_users
  end

  def following
    @following = @user.following.where.not(id: current_user.id)
  end

  def followers
    @followers = @user.followers.where.not(id: current_user.id)
  end

  def likes
    @purrs = @user.liked_purrs
  end

  private

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(u, options={})
    if u.avatar.attached?
      image_tag u.avatar, options
    else
      image_tag 'default-profile-pic.png', options
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/purrs_helper.rb
module PurrsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Purrter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>

  <body>
    <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <div class="container text-center"><%= notice %></div>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <div class="container text-center"><%= alert %></div>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <% if current_user %>
      <%= render 'shared/modal' %>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<section class="container-fluid main">
  <div class="container no-padding-x-sm">
    <div class="row">
      <div class="d-none d-md-block col-md-4 col-lg-3">
        <div class="home-card">
          <img class="card-img-top" src="<%= asset_path 'background-example.jpeg' %>">
          <div class="card-body home-profile container">
            <div class="home-profile-main">
              <div class="row">
                <div class="col-4">
                <%= link_to(user_avatar(current_user, class: "home-profile-img"), user_url(current_user)) %>
                </div>
                <div class="col-8 d-flex flex-column justify-content-center">
                  <p class="home-profile-title">
                    <a href='<%= user_url(current_user) %>'>
                      <strong><%= current_user.name %></strong>
                      <small class="text-muted">
                        <%= "@#{current_user.username}" %>
                      </small>
                    </a>
                  </p>
                </div>
              </div>
            </div>
            <div class="home-profile-stats">
              <ul class="home-stats d-flex justify-content-between">
                <li><span class="text-muted">Purrs</span><span class="stat-count"><%= @user.purrs.count %></span>
                <li><span class="text-muted">Followers</span><span class="stat-count"><%= @user.followers.count %></span>
              </ul>
            </div>
          </div>
        </div>
        <div class="d-none d-md-block d-lg-none mt-3">
          <%= render 'shared/who_to_follow.html.erb' %>
        </div>
      </div>
      <section class="col-12 col-md-8 col-lg-6">
        <%= render 'shared/home_content.html.erb' %>
      </section>
      <div class="d-none d-lg-block col-3">
        <%= render 'shared/who_to_follow.html.erb' %>
      </div>
    </div>
  </div>
</section>

app/views/purrs/edit.html.erb
<section class="container-fluid main">
  <div class="container no-padding-x-sm">
    <div class="row">
      <section class="col-12 col-md-8 col-lg">
        <div class="purr-container">
          <div class="post-form">
            <%= form_for @purr do |f| %>
              <div class="form-content">
                <%= link_to(user_avatar(current_user), user_url(current_user)) %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.text_area :content, autofocus: true, autocomplete: "content", class: "form-control",
                                  placeholder: "What's Cattening?", required: "", maxlength: "140" %>
              </div>
              <%= f.submit "Edit", class: "form-group btn btn-primary d-block ml-auto my-1" %>
            <% end %>
          </div>
        </div>
      </section>
    </div>
  </div>
</section>

app/views/shared/_follow_button.html.erb
<% user = user.nil? ? @user : user %>
<% if !current_user.following?(user) %>
  <%= form_for(current_user.active_relationships.build) do |f| %>
    <div><%= hidden_field_tag :followed_id, user.id %></div>
    <%= f.submit "Follow", class: "btn btn-primary ml-auto d-block" %>
  <% end %>
<% else %>
  <%= form_for(current_user.active_relationships.find_by(followed_id: user.id), html: { method: :delete }) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-outline-primary ml-auto d-block" %>
  <% end %>
<% end %>

app/views/shared/_home_content.html.erb
<div class="purr-container">
  <div class="post-form">
    <%= form_for @new_purr do |f| %>
      <div class="form-content">
        <%= link_to(user_avatar(current_user), user_url(current_user)) %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.text_field :content, autofocus: true, autocomplete: "content", class: "form-control",
                          placeholder: "What's Cattening?", required: "", maxlength: "140" %>
      </div>
      <%= f.submit "Purr", class: "form-group btn btn-primary d-block ml-auto my-1" %>
    <% end %>
  </div>
  <%= render "shared/purrs.html.erb" %>
</div>

app/views/shared/_modal.html.erb
<div class="modal fade" id="purrModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add New Purr</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="purr-form">
          <%= form_for @new_purr do |f| %>
            <div class="form-content">
            <%= link_to(user_avatar(current_user), user_url(current_user)) %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.text_field :content, autofocus: true, autocomplete: "content", class: "form-control",
                                placeholder: "What's Cattening?", required: "" %>
            </div>
            <%= f.submit "Purr", class: "form-group btn btn-primary d-block ml-auto my-1" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light navbar-expand-md bg-primary fixed-top">
  <div class="container">
    <a href='<%= user_signed_in? ? home_path : root_path %>' class="navbar-brand">Purrter</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <li class="nav-item">
            <a class="nav-link" href="/home">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/explore">Explore</a>
          </li>
          <li class="nav-item">
            <div class="dropdown">
              <%= link_to(user_avatar(current_user, class: "nav-profile-img"), '#', 
                "data-toggle" => "dropdown", class: "d-none d-md-inline") %>
              <%= link_to "Options", '#', "data-toggle" => "dropdown", class: "nav-link d-inline-block d-md-none" %>
              <div class="dropdown-menu">
                <a class="dropdown-item" href='<%= user_url(current_user) %>'>Profile</a>
                <a class="dropdown-item" href="<%= edit_user_registration_path @user %>">Settings</a>
                <div class="dropdown-divider"></div>
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "dropdown-item" %>
              </div>
            </div>
          </li>
          <li class="nav-item">
            <button class="btn btn-light" data-toggle="modal" data-target="#purrModal"><i class="fas fa-plus"></i> Purr</button>
          </li>
        <% else %>
          <li class="nav-item d-none d-md-inline-block">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-light" %>
          </li>
          <li class="nav-item d-none d-md-inline-block">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-light ml-2" %>
          </li>
          <li class="nav-item d-md-none">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item d-md-none">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_purr.html.erb
<div class="purr d-flex position-relative<%= ' bottom-purr' if bottom %><%= ' top-purr' if top %>">

  <% if current_user.id == purr.user.id %>
    <div class="dropdown position-absolute purr-dots">
      <button class="btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-h"></i>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= link_to 'Edit', edit_purr_path(purr), class: "dropdown-item" %>
        <%= form_for(purr, html: { method: :delete }) do |f| %>
          <%= f.submit "Delete", class: "dropdown-item" %>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="purr-img-container">
    <%= link_to(user_avatar(purr.user), user_url(purr.user)) %>
  </div>
  <div class="purr-content-container">
    <p class="purr-title"><a href="<%= user_url(purr.user) %>"><strong><%= purr.user.name %></strong> <small class="text-muted"><%= "@#{purr.user.username}" %></small></a></p>
    <p class="purr-content"><%= purr.content %></p>
    <div class="action-bar mb-2">
      <div>
        <i class="fas fa-reply" data-toggle="tooltip" data-placement="top" title="Coming Soon!"></i>
      </div>
      <div>
        <i class="fas fa-retweet" data-toggle="tooltip" data-placement="top" title="Coming Soon!"></i>
      </div>
      <div>
        <%= render 'shared/like_button.html.erb', purr: purr %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_user.html.erb
<div class="user d-flex">
  <div class="user-img-container">
    <%= link_to(user_avatar(user), user_url(user)) %>
  </div>
  <div class="user-content-container d-flex justify-content-between w-100">
    <div class="user-title d-flex flex-column">
      <a href='<%= user_url(user) %>'>
        <p class="mb-0"><strong><%= user.name %></strong></p>
        <small class="text-muted d-block"><%= "@#{user.username}" %></small>
      </a>
    </div>
    <div class="d-flex flex-column justify-content-center">
      <%= render "shared/follow_button.html.erb", user: user %>
    </div>
  </div>
</div>

app/views/shared/_who_to_follow.html.erb
<div class="who-to-follow container">
  <h5>Who to Follow</h5>
  <% for u in @to_follow_users do %>
    <div class="follow-profile d-flex">
      <div>
        <%= link_to(user_avatar(current_user, class: "follow-profile-img"), user_url(u)) %>
      </div>
      <div class="ml-3">
        <p class="follow-profile-title">
          <a href='<%= user_url(u) %>'>
            <strong><%= u.name %></strong>
            <small class="text-muted">
              <%= "@#{u.username}" %>
            </small>
          </a>
        </p>
        <%= render 'shared/small_follow_button.html.erb', {linked_user: u} %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="banner" style="background-image: url(<%= asset_path 'background-example.jpeg' %>)">
</div>
<section class="container-fluid stats-banner">
  <div class="container">
    <div class="row d-md-none">
      <div class="col-12">
        <div class="profile-mobile-head d-flex mt-1">
          <%= user_avatar @user, class: "profile-mobile-img" %>
          <div class="d-flex flex-column justify-content-center ml-auto">
            <%= render 'shared/profile_button' %>
          </div>
        </div>
        <div class="mt-1">
          <h6 class="profile-title mb-0"><%= @user.name %></h6>
          <small class="text-muted"><%= "@#{@user.username}" %></small>
          <p><i class="fas fa-calendar-alt"></i> Joined <%= @user.created_at.strftime("%B %Y") %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="d-none d-md-block col-md-4 col-lg-3"></div>
      <div class="col-12 col-md-8 col-lg-6">
        <ul class="stats-bar d-flex d-md-block justify-content-between">
          <li><a href="<%= user_url(@user) %>"><span class="text-muted">Purrs</span><span><%= @user.purrs.count %></span></a>
          <li><a href="<%= following_user_path(@user) %>"><span class="text-muted">Following</span><span><%= @user.following.count %></span></span></a>
          <li><a href="<%= followers_user_path(@user) %>" class="active"><span class="text-muted">Followers</span><span><%= @user.followers.count %></span></a>
          <li><a href="<%= likes_user_path(@user) %>"><span class="text-muted">Likes</span><span><%= @user.liked_purrs.count %></span></a>
        </ul>
      </div>
      <div class="d-none d-lg-flex col-3 flex-column justify-content-center">
        <%= render 'shared/profile_button' %>
      </div>
    </div>
  </div>
</section>
<section class="container-fluid main">
  <div class="container">
    <div class="row">
      <section class="d-none d-md-block col-md-4 col-lg-3">
        <div class="row">
          <div class="col-10">
            <%= user_avatar @user, class: "profile-img" %>
            <div>
              <h5 class="profile-title"><%= @user.name %></h5>
              <small class="text-muted"><%= "@#{@user.username}" %></small>
              <p><i class="fas fa-calendar-alt"></i> Joined <%= @user.created_at.strftime("%B %Y") %>
            </div>
          </div>
        </div>
        <div class="d-none d-md-block d-lg-none">
          <%= render 'shared/profile_button' %>
        </div>
        <div class="d-none d-md-block d-lg-none mt-md-3 mt-lg-0">
          <%= render 'shared/who_to_follow.html.erb' %>
        </div>
      </section>
      <section class="col-md-8 col-lg-6 user-container">
        <% for u in @followers do %>
          <%= render 'shared/user.html.erb', user: u %>
        <% end %>
      </section>
      <section class="d-none d-lg-block col-lg-3">
        <%= render 'shared/who_to_follow.html.erb' %>
      </section>
    </div>
  </div>
</section>

app/views/users/following.html.erb
<div class="banner" style="background-image: url(<%= asset_path 'background-example.jpeg' %>)">
</div>
<section class="container-fluid stats-banner">
  <div class="container">
    <div class="row d-md-none">
      <div class="col-12">
        <div class="profile-mobile-head d-flex mt-1">
          <%= user_avatar @user, class: "profile-mobile-img" %>
          <div class="d-flex flex-column justify-content-center ml-auto">
            <%= render 'shared/profile_button' %>
          </div>
        </div>
        <div class="mt-1">
          <h6 class="profile-title mb-0"><%= @user.name %></h6>
          <small class="text-muted"><%= "@#{@user.username}" %></small>
          <p><i class="fas fa-calendar-alt"></i> Joined <%= @user.created_at.strftime("%B %Y") %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="d-none d-md-block col-md-4 col-lg-3"></div>
      <div class="col-12 col-md-8 col-lg-6">
        <ul class="stats-bar d-flex d-md-block justify-content-between">
          <li><a href="<%= user_url(@user) %>"><span class="text-muted">Purrs</span><span><%= @user.purrs.count %></span></a>
          <li><a href="<%= following_user_path(@user) %>" class="active"><span class="text-muted">Following</span><span><%= @user.following.count %></span></span></a>
          <li><a href="<%= followers_user_path(@user) %>"><span class="text-muted">Followers</span><span><%= @user.followers.count %></span></a>
          <li><a href="<%= likes_user_path(@user) %>"><span class="text-muted">Likes</span><span><%= @user.liked_purrs.count %></span></a>
        </ul>
      </div>
      <div class="d-none d-lg-flex col-3 flex-column justify-content-center">
        <%= render 'shared/profile_button' %>
      </div>
    </div>
  </div>
</section>
<section class="container-fluid main">
  <div class="container">
    <div class="row">
      <section class="d-none d-md-block col-md-4 col-lg-3">
        <div class="row">
          <div class="col-10">
            <%= user_avatar @user, class: "profile-img" %>
            <div>
              <h5 class="profile-title"><%= @user.name %></h5>
              <small class="text-muted"><%= "@#{@user.username}" %></small>
              <p><i class="fas fa-calendar-alt"></i> Joined <%= @user.created_at.strftime("%B %Y") %>
            </div>
          </div>
        </div>
        <div class="d-none d-md-block d-lg-none">
          <%= render 'shared/profile_button' %>
        </div>
        <div class="d-none d-md-block d-lg-none mt-md-3 mt-lg-0">
          <%= render 'shared/who_to_follow.html.erb' %>
        </div>
      </section>
      <section class="col-md-8 col-lg-6 user-container">
        <% for u in @following do %>
          <%= render 'shared/user.html.erb', user: u %>
        <% end %>
      </section>
      <section class="d-none d-lg-block col-lg-3">
        <%= render 'shared/who_to_follow.html.erb' %>
      </section>
    </div>
  </div>
</section>

app/views/users/likes.html.erb
<div class="banner" style="background-image: url(<%= asset_path 'background-example.jpeg' %>)">
</div>
<section class="container-fluid stats-banner">
  <div class="container">
    <div class="row d-md-none">
      <div class="col-12">
        <div class="profile-mobile-head d-flex mt-1">
          <%= user_avatar @user, class: "profile-mobile-img" %>
          <div class="d-flex flex-column justify-content-center ml-auto">
            <%= render 'shared/profile_button' %>
          </div>
        </div>
        <div class="mt-1">
          <h6 class="profile-title mb-0"><%= @user.name %></h6>
          <small class="text-muted"><%= "@#{@user.username}" %></small>
          <p><i class="fas fa-calendar-alt"></i> Joined <%= @user.created_at.strftime("%B %Y") %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="d-none d-md-block col-md-4 col-lg-3"></div>
      <div class="col-12 col-md-8 col-lg-6">
        <ul class="stats-bar d-flex d-md-block justify-content-between">
          <li><a href="<%= user_url(@user) %>"><span class="text-muted">Purrs</span><span><%= @user.purrs.count %></span></a>
          <li><a href="<%= following_user_path(@user) %>"><span class="text-muted">Following</span><span><%= @user.following.count %></span></span></a>
          <li><a href="<%= followers_user_path(@user) %>"><span class="text-muted">Followers</span><span><%= @user.followers.count %></span></a>
          <li><a href="<%= likes_user_path(@user) %>" class="active"><span class="text-muted">Likes</span><span><%= @user.liked_purrs.count %></span></a>
        </ul>
      </div>
      <div class="d-none d-lg-flex col-3 flex-column justify-content-center">
        <%= render 'shared/profile_button' %>
      </div>
    </div>
  </div>
</section>
<section class="container-fluid main">
  <div class="container">
    <div class="row">
      <section class="d-none d-md-block col-md-4 col-lg-3">
        <div class="row">
          <div class="col-10">
            <%= user_avatar @user, class: "profile-img" %>
            <div>
              <h5 class="profile-title"><%= @user.name %></h5>
              <small class="text-muted"><%= "@#{@user.username}" %></small>
              <p><i class="fas fa-calendar-alt"></i> Joined <%= @user.created_at.strftime("%B %Y") %>
            </div>
          </div>
        </div>
        <div class="d-none d-md-block d-lg-none">
          <%= render 'shared/profile_button' %>
        </div>
        <div class="d-none d-md-block d-lg-none mt-md-3 mt-lg-0">
          <%= render 'shared/who_to_follow.html.erb' %>
        </div>
      </section>
      <section class="col-md-8 col-lg-6 purr-container">
        <%= render 'shared/purrs.html.erb' %>
      </section>
      <section class="d-none d-lg-block col-lg-3">
        <%= render 'shared/who_to_follow.html.erb' %>
      </section>
    </div>
  </div>
</section>